name: Auto-assign PR author

on:
    pull_request:
        types: [opened, reopened, ready_for_review]

permissions:
    contents: read
    pull-requests: write
    issues: write

jobs:
    assign-author:
        runs-on: ubuntu-latest
        steps:
            - name: Assign PR author if unassigned
              uses: actions/github-script@v7
              with:
                  script: |
                      const pr = context.payload.pull_request;
                      const alreadyAssigned = (pr.assignees || []).length > 0;
                      if (alreadyAssigned) {
                        core.info('PR already has assignees. Skipping.');
                        return;
                      }
                      
                      const author = pr.user.login;
                      core.info(`Assigning PR author: ${author}`);
                      
                      await github.rest.issues.addAssignees({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: pr.number,
                        assignees: [author],
                      });
